<?php
if(!defined('ABSPATH'))exit;
define('TERTTUS_VERSION','1.0.0');
define('TERTTUS_UPDATE_METADATA','https://raw.githubusercontent.com/Niklas-Terttu/terttus-wordpress-theme/main/update.json');
function terttus_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('custom-logo',['height'=>80,'width'=>260,'flex-height'=>true,'flex-width'=>true]);add_theme_support('woocommerce');add_theme_support('wc-product-gallery-zoom');add_theme_support('wc-product-gallery-lightbox');add_theme_support('wc-product-gallery-slider');register_nav_menus(['primary'=>__('Primær menu','terttus'),'footer'=>__('Footer menu','terttus')]);}
add_action('after_setup_theme','terttus_setup');
function terttus_assets(){wp_enqueue_style('terttus-style',get_stylesheet_uri(),[],TERTTUS_VERSION);wp_enqueue_script('terttus-theme',get_template_directory_uri().'/assets/theme.js',[],TERTTUS_VERSION,true);}add_action('wp_enqueue_scripts','terttus_assets');
function terttus_widgets(){register_sidebar(['name'=>'Shop Sidebar','id'=>'shop-sidebar','before_widget'=>'<section class="widget">','after_widget'=>'</section>','before_title'=>'<h3>','after_title'=>'</h3>']);}add_action('widgets_init','terttus_widgets');
function terttus_customize($w){$w->add_section('terttus_shop',['title'=>'Terttus webshop','priority'=>30]);foreach(['shipping_text'=>['Topbar tekst','🚚 Fri fragt ved køb over 499 kr. · Levering 1–3 hverdage'],'hero_title'=>['Hero overskrift','Gør dit hjem smartere med Terttus'],'hero_text'=>['Hero tekst','IT, elektronik og smart home – udvalgt af en entusiast, til fornuftige priser og med ordentlig support.']] as $id=>$x){$w->add_setting($id,['default'=>$x[1],'sanitize_callback'=>'sanitize_text_field']);$w->add_control($id,['section'=>'terttus_shop','label'=>$x[0],'type'=>'text']);}}}$GLOBALS['wp_customize']??null;add_action('customize_register','terttus_customize');
function terttus_meta(){$r=wp_remote_get(TERTTUS_UPDATE_METADATA,['timeout'=>10]);if(is_wp_error($r)||200!==wp_remote_retrieve_response_code($r))return null;$d=json_decode(wp_remote_retrieve_body($r),true);return is_array($d)?$d:null;}
function terttus_update_check($t){$d=terttus_meta();if(empty($d['version'])||version_compare(TERTTUS_VERSION,$d['version'],'>='))return $t;$theme=wp_get_theme();$t->response[$theme->get_stylesheet()]=['theme'=>$theme->get_stylesheet(),'new_version'=>$d['version'],'url'=>$d['details_url']??'','package'=>$d['download_url']??''];return $t;}add_filter('pre_set_site_transient_update_themes','terttus_update_check');
